//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ACTUALIZAR_STOCK
    {
        public int ID_ACTUALIZAR { get; set; }
        public int ID_EMPRESA { get; set; }
        public int ID_TIPO_COMPROBANTE { get; set; }
        public string NUMERO_DOCUMENTO { get; set; }
        public string GUIA { get; set; }
        public int ID_PRODUCTO { get; set; }
        public int ID_ALMACEN { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRE_COMPRA { get; set; }
        public Nullable<decimal> PRE_VENTA_UND { get; set; }
        public Nullable<decimal> PRE_VENTA_UND_DOLAR { get; set; }
        public Nullable<System.DateTime> FEC_OPERACION { get; set; }
        public string USU_CREACION { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
        public string USU_MODIFICA { get; set; }
        public Nullable<System.DateTime> FEC_MODIFICA { get; set; }
        public string FLG_ESTADO { get; set; }
    
        public virtual T_M_ALMACEN T_M_ALMACEN { get; set; }
    }
}
