//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_CORRELATIVO_PRODUCTO
    {
        public int ID_CORRELATIVO { get; set; }
        public string NUM_CORRELATIVO { get; set; }
        public Nullable<int> ID_EMPRESA { get; set; }
        public string ANIO { get; set; }
    }
}
