//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_D_PARAMETRO
    {
        public int ID_D_PARAMETRO { get; set; }
        public Nullable<int> ID_PARAMETRO { get; set; }
        public Nullable<decimal> VALOR_D { get; set; }
        public Nullable<int> VALOR_I { get; set; }
        public Nullable<System.DateTime> FEC_INICIO { get; set; }
        public Nullable<System.DateTime> FEC_FIN { get; set; }
        public string FLG_ESTADO { get; set; }
        public string USU_CREACION { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
        public string USU_MODIFICA { get; set; }
        public Nullable<System.DateTime> FEC_MODIFICA { get; set; }
    
        public virtual T_M_PARAMETRO T_M_PARAMETRO { get; set; }
    }
}
