//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_D_VENTA
    {
        public int ID_DETALLE { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public int ID_PERSONAL { get; set; }
        public int ID_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
    
        public virtual T_M_PRODUCTO T_M_PRODUCTO { get; set; }
        public virtual T_M_VENTA T_M_VENTA { get; set; }
    }
}
