//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_D_ENVIO_RESUMEN
    {
        public int ID_DETALLE { get; set; }
        public int ID_ENVIO_RESUMEN { get; set; }
        public int ID_COMPROBANTE_SUNAT { get; set; }
        public Nullable<short> CONDICION { get; set; }
    
        public virtual T_M_ENVIO_RESUMEN T_M_ENVIO_RESUMEN { get; set; }
        public virtual T_M_COMPROBANTE_SUNAT T_M_COMPROBANTE_SUNAT { get; set; }
    }
}
