//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_D_DOCUMENTOS_VENTAS
    {
        public decimal ID_DOCUMENTO_VENTA { get; set; }
        public Nullable<int> ID_VENTA { get; set; }
        public string CODIGO_ARCHIVO { get; set; }
        public string NOMBRE_ARCHIVO { get; set; }
        public string EXTENSION_ARCHIVO { get; set; }
        public Nullable<System.DateTime> FEC_CREARION { get; set; }
        public string USU_CREACCION { get; set; }
        public Nullable<System.DateTime> FEC_MODIFICACION { get; set; }
        public string USU_MODIFICACION { get; set; }
    
        public virtual T_M_VENTA T_M_VENTA { get; set; }
    }
}
