//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_D_CORTE
    {
        public int ID_DETALLE { get; set; }
        public int ID_CORTE { get; set; }
        public int ID_SERVICIO { get; set; }
        public int CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
    
        public virtual T_M_CORTE T_M_CORTE { get; set; }
        public virtual T_M_SERVICIO T_M_SERVICIO { get; set; }
    }
}
