//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_D_COTIZACION
    {
        public int ID_D_COTIZACION { get; set; }
        public Nullable<int> ID_COTIZACION { get; set; }
        public string NUM_COTIZACION { get; set; }
        public Nullable<int> ID_PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
    
        public virtual T_M_COTIZACION T_M_COTIZACION { get; set; }
    }
}
