//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_DISTRITO
    {
        public int ID_DISTRITO { get; set; }
        public string COD_DEPARTAMENTO { get; set; }
        public string COD_PROVINCIA { get; set; }
        public string COD_DISTRITO { get; set; }
        public string DISTRITO { get; set; }
        public string UBIGEO { get; set; }
    }
}
