//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_EMPRESA
    {
        public int ID_EMPRESA { get; set; }
        public string RUC { get; set; }
        public string R_SOCIAL { get; set; }
        public string NOM_COMERCIAL { get; set; }
        public string COD_DEPARTAMENTO { get; set; }
        public string COD_PROVINCIA { get; set; }
        public string COD_DISTRITO { get; set; }
        public string UBIGEO { get; set; }
        public string DIRECCION { get; set; }
        public string FLG_ESTADO { get; set; }
        public string USU_CREACION { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
        public string USU_MODIFICA { get; set; }
        public Nullable<System.DateTime> FEC_MODIFICA { get; set; }
    }
}
