//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_USUARIO
    {
        public int ID_USUARIO { get; set; }
        public int ID_EMPRESA { get; set; }
        public string USUARIO { get; set; }
        public string CLAVE { get; set; }
        public int ID_PERFIL { get; set; }
        public int ID_PERSONAL { get; set; }
        public string FLG_ESTADO { get; set; }
        public string USU_CREACION { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
        public string USU_MODIFICA { get; set; }
        public Nullable<System.DateTime> FEC_MODIFICA { get; set; }
    
        public virtual T_M_PERFIL T_M_PERFIL { get; set; }
        public virtual T_M_PERSONAL T_M_PERSONAL { get; set; }
    }
}
