//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_PARAMETRO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_M_PARAMETRO()
        {
            //this.T_D_PARAMETRO = new HashSet<T_D_PARAMETRO>();
        }
    
        public int ID_PARAMETRO { get; set; }
        public int ID_EMPRESA { get; set; }
        public string COD_PARAMETRO { get; set; }
        public string DESC_PARAMETRO { get; set; }
        public string TIPO_PARAMETRO { get; set; }
        public Nullable<decimal> VALOR_D { get; set; }
        public string VALOR_S { get; set; }
        public Nullable<int> VALOR_I { get; set; }
        public string FLG_ESTADO { get; set; }
        public string USU_CREACION { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
        public string USU_MODIFICA { get; set; }
        public Nullable<System.DateTime> FEC_MODIFICA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public  ICollection<T_D_PARAMETRO> T_D_PARAMETRO { get; set; }
    }
}
