//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_ENVIO_RESUMEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_M_ENVIO_RESUMEN()
        {
            this.T_D_ENVIO_RESUMEN = new HashSet<T_D_ENVIO_RESUMEN>();
        }
    
        public int ID_ENVIO_RESUMEN { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_REFERENCIA { get; set; }
        public Nullable<int> CORRELATIVO { get; set; }
        public Nullable<int> RESUMEN { get; set; }
        public Nullable<int> BAJA { get; set; }
        public string NOMBRE_XML { get; set; }
        public string MENSAJE_SUNAT { get; set; }
        public string CODIGO_SUNAT { get; set; }
        public string ESTADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_D_ENVIO_RESUMEN> T_D_ENVIO_RESUMEN { get; set; }
    }
}
