//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_CUOTA
    {
        public int ID_CUOTA { get; set; }
        public int ID_COMPROBANTE_SUNAT { get; set; }
        public string NUMERO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public string ESTADO { get; set; }
    
        public virtual T_M_COMPROBANTE_SUNAT T_M_COMPROBANTE_SUNAT { get; set; }
    }
}
