//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_M_COMPROBANTE_SUNAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_M_COMPROBANTE_SUNAT()
        {
            this.T_D_ENVIO_RESUMEN = new HashSet<T_D_ENVIO_RESUMEN>();
            this.T_M_CUOTA = new HashSet<T_M_CUOTA>();
        }
    
        public int ID_COMPROBANTE_SUNAT { get; set; }
        public int ID_EMPRESA { get; set; }
        public int ID_TIPO_COMPROBANTE { get; set; }
        public int ID_SERIE { get; set; }
        public string SERIE { get; set; }
        public int CORRELATIVO { get; set; }
        public string FORMA_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_EMISION { get; set; }
        public Nullable<System.DateTime> FECHA_VENCIMIENTO { get; set; }
        public int ID_MONEDA { get; set; }
        public Nullable<decimal> OP_GRAVADAS { get; set; }
        public Nullable<decimal> OP_EXONERADAS { get; set; }
        public Nullable<decimal> OP_INAFECTAS { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public int ID_CLIENTE { get; set; }
        public string TIPO_COMPROBANTE_REF_ID { get; set; }
        public string SERIE_REF { get; set; }
        public Nullable<int> CORRELATIVO_REF { get; set; }
        public string COD_MOTIVO { get; set; }
        public string NOMBRE_XML { get; set; }
        public string XML_BASE64 { get; set; }
        public string COD_HASH { get; set; }
        public string CDR_BASE64 { get; set; }
        public string COD_SUNAT { get; set; }
        public string MENSAJE_SUNAT { get; set; }
        public string ESTADO_COMPROBANTE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_D_ENVIO_RESUMEN> T_D_ENVIO_RESUMEN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_M_CUOTA> T_M_CUOTA { get; set; }
        public virtual T_M_MONEDA T_M_MONEDA { get; set; }
        public virtual T_M_SERIE T_M_SERIE { get; set; }
        public virtual T_TIPO_COMPROBANTE T_TIPO_COMPROBANTE { get; set; }
    }
}
