//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TIPO_AFECTACION
    {
        public int ID_AFECTACION { get; set; }
        public string COD_AFECTACION { get; set; }
        public string DESC_AFECTACION { get; set; }
        public string LETRA { get; set; }
        public string COD_TRIBUTO { get; set; }
        public string DESC_TRIBUTO { get; set; }
        public string TIPO_TRIBUTO { get; set; }
    }
}
