//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TIPO_DOCUMENTO
    {
        public int ID_DOCUMENTO { get; set; }
        public string COD_DOCUMENTO { get; set; }
        public string DOCUMENTO { get; set; }
    }
}
