//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TIPO_COMPROBANTE
    {
        public int ID_TIPO_COMPROBANTE { get; set; }
        public string COD_TIPO_COMPROBANTE { get; set; }
        public string DESC_TIPO_COMPROBANTE { get; set; }
    }
}
