//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_CORTE
    {
        public int ID_DETALLE { get; set; }
        public int ID_CORTE { get; set; }
        public string VOUCHER { get; set; }
        public string PERSONAL { get; set; }
        public string CLIENTE { get; set; }
        public string DES_SERVICIO { get; set; }
        public int CANTIDAD { get; set; }
        public decimal PRECIO { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public Nullable<System.DateTime> FEC_CORTE { get; set; }
        public string USUARIO { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<int> MES { get; set; }
    }
}
