//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_KARDEX
    {
        public int ID_KARDEX { get; set; }
        public int ID_PRODUCTO { get; set; }
        public Nullable<int> STOCK { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<int> ID_MONEDA { get; set; }
        public Nullable<decimal> PRECIO_VENTA { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
        public Nullable<decimal> TIPO_CAMBIO { get; set; }
        public Nullable<System.DateTime> FEC_KARDEX { get; set; }
        public string DESC_TIPO_COMPROBANTE { get; set; }
        public Nullable<System.DateTime> FEC_DETALLE_KARDEX { get; set; }
        public string NUM_DOCUMENTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public decimal PRECIO_SOLES { get; set; }
        public decimal PRECIO_DOLAR { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string TIPO_TRANSACCION { get; set; }
        public Nullable<decimal> CANTIDAD_SALDO { get; set; }
        public Nullable<decimal> PRECIO_SALDO { get; set; }
        public Nullable<decimal> TOTAL_SALDO { get; set; }
        public string USU_CREACION { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
    }
}
