//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_PRODUCTO
    {
        public int ID_EMPRESA { get; set; }
        public string DESC_CATEGORIA { get; set; }
        public Nullable<int> ID_CATEGORIA { get; set; }
        public int ID_PRODUCTO { get; set; }
        public string COD_PRODUCTO { get; set; }
        public string DES_ALMACEN { get; set; }
        public string DES_CLASE { get; set; }
        public string PRODUCTO { get; set; }
        public string DES_UNIDAD_MEDIDA { get; set; }
        public string DES_MODELO { get; set; }
        public string DES_MARCA { get; set; }
        public string NOM_FILE { get; set; }
        public string RUTA { get; set; }
        public Nullable<int> STOCK { get; set; }
        public Nullable<decimal> PRECIO_COMPRA { get; set; }
        public Nullable<decimal> PRECIO_VENTA { get; set; }
        public Nullable<decimal> PRECIO_VENTA_DOLAR { get; set; }
        public Nullable<System.DateTime> FEC_COMPRA { get; set; }
        public string FLG_ESTADO { get; set; }
        public string USU_CREACION { get; set; }
        public Nullable<System.DateTime> FEC_CREACION { get; set; }
        public string USU_MODIFICA { get; set; }
        public Nullable<System.DateTime> FEC_MODIFICA { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<int> MES { get; set; }
    }
}
