//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Barberia.Entidad
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_VENTA
    {
        public int ID_VENTA { get; set; }
        public int ID_EMPRESA { get; set; }
        public Nullable<int> ID_MONEDA { get; set; }
        public string DESC_MONDEDA { get; set; }
        public string VOUCHER { get; set; }
        public string PERSONAL { get; set; }
        public string CLIENTE { get; set; }
        public string PRODUCTO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<decimal> IMPORTE { get; set; }
        public Nullable<decimal> TOTAL_IMPORTE { get; set; }
        public Nullable<decimal> IGV { get; set; }
        public Nullable<decimal> DESCT_TOTAL { get; set; }
        public Nullable<decimal> TOTAL { get; set; }
        public string EFECTIVO { get; set; }
        public string VUELTO { get; set; }
        public string USUARIO { get; set; }
        public Nullable<System.DateTime> FEC_VENTA { get; set; }
        public Nullable<int> ANIO { get; set; }
        public Nullable<int> MES { get; set; }
    }
}
